<Project Sdk="MSTest.Sdk">
	<PropertyGroup>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Medienstudio.Azure.Data.Tables.Extensions\Medienstudio.Azure.Data.Tables.Extensions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Data.Tables" />
	</ItemGroup>
</Project>
