# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  mainProj: 'Medienstudio.Azure.Data.Tables.Extensions'
  testProj: 'Medienstudio.Azure.Data.Tables.Extensions.Tests'
  buildPlatform: Any CPU
  buildConfiguration: Release
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x
          dotnet-version: 6.0.x
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
      - name: Install & run Azurite
        run: |
         npm install -g azurite
         mkdir azurite
         azurite --silent --location azurite --debug azurite/debug.log
      - name: Build Solution
        run: dotnet build src/${{ env.mainProj }}.sln -c Release
      - name: Test Solution
        run: dotnet test src/${{ env.testProj }}/${{ env.testProj }}.csproj
