# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  mainProj: 'Medienstudio.Azure.Data.Tables.Extensions'
  testProj: 'Medienstudio.Azure.Data.Tables.Extensions.Tests'
  mainCSVProj: 'Medienstudio.Azure.Data.Tables.CSV'
  testCSVProj: 'Medienstudio.Azure.Data.Tables.CSV.Tests'
  buildPlatform: Any CPU
  buildConfiguration: Release
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install & run Azurite
        run: npm install -g azurite
        # https://github.com/Azure/Azurite/issues/451#issuecomment-639398801
      - name: Run Azurite in Background
        shell: bash
        run: azurite &
      - name: Build Solution
        run: dotnet build src/${{ env.mainProj }}.sln -c Release
      - name: Test Extensions
        run: dotnet test src/${{ env.testProj }}/${{ env.testProj }}.csproj
      - name: Test CSV Extensions
        run: dotnet test src/${{ env.testCSVProj }}/${{ env.testCSVProj }}.csproj
