# This is a basic workflow to help you get started with Actions

name: CD Extensions

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Build & Package
      run: |
        cd src/Medienstudio.Azure.Data.Tables.Extensions
        dotnet pack -c Release -o out
    - name: PushNuget
      run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGETSECRET}} --skip-duplicate
